### ISSUE TITLE
php 5.4

### ISSUE THREAD

**Issue by XLegion** [malkusch/lock#3]
What features of PHP 5.5 do you use?
Is there any way to downgrade PHP version to 5.4 in composer.json?

**Comment by malkusch** [comment]
> What features of PHP 5.5 do you use?

Dunno exactly, in the tests I use [`::class`](https://github.com/malkusch/lock/blob/master/tests/mutex/LockMutexTest.php#L28). But more important I'm using [`finally`](https://github.com/malkusch/lock/blob/master/classes/mutex/LockMutex.php#L40) to guarantee that the lock will be released after the critical code.

> Is there any way to downgrade PHP version to 5.4 in composer.json?

Well sure, you could fork that and refactor the code to work in PHP-5.4. But let me discourage you from doing so. [PHP-5.4 has reached its end of life](http://php.net/eol.php). Please consider upgrading your PHP version.
