### ISSUE TITLE
Reconsider requiring ATTR_AUTOCOMMIT to be disabled (on MySQL)

### ISSUE THREAD

**Issue by rubenvandeven** [malkusch/lock#4]
Hi,

I just ran into the problem that the TransactionalMutex requires a PDO connection with ATTR_AUTOCOMMIT disabled.
As I see the code and consider [the MySQL documentation on AUTOCOMMIT](http://dev.mysql.com/doc/refman/5.7/en/commit.html), it seems autocommit is already disabled when `$this->pdo->beginTransaction();` is ran (this state lasts until the `commit()`).
Could you confirm whether my thought is correct? If  so, would it be possible to skip the AUTOCOMMIT check -- at least for a MySQL PDO connection?

Thank you!

**Comment by malkusch** [comment]
Thank you for this information. I wasn't aware of that behaviour. I will omit that check for MySQL. However I cannot do so in general as `ATTR_AUTOCOMMIT` has an effect on [other DBS](https://github.com/php/php-src/search?l=c&q=autocommit&type=Code).
